Reset gesture on visibilitychange. Fixes #239.
Exception: swiping up to the app switcher and then back down to the same app still causes unintended gesture touchmove.